// packages/svelte-live-chat/src/components/ChatInput.svelte
<script lang="ts">
    export let messageHandler: (msg: string) => void;
    export let placeholder: string = "Placeholder";
    let input: string = "";

    const sendMessage = () => {
        messageHandler(input);
        input = "";
    };
</script>

<form on:submit|preventDefault>
    <input bind:value={input} type="text" placeholder={placeholder} />
    <button disabled={!input} on:click={sendMessage}>SEND</button>
</form>

<style lang="scss" scoped>
    form {
        display: flex;
        
        input {
            flex-grow: 3;
        }

        button {
            flex-grow: 1;
        }

        > * {
            padding: .25rem;
        }
    }
</style>

// packages/vue3-live-chat/src/components/ChatInput.vue
<script setup lang="ts">
import { Ref, ref } from 'vue';

const props = defineProps<{ isDisabled: boolean, placeholder: string }>();
const input: Ref<string | null> = ref(null);

const emit = defineEmits<{
  (e: 'submitMessage', messagePayload: string): void
}>()

const sendMessage = () => {
    if(!input.value) return;
    emit('submitMessage', input.value);
    input.value = "";
};

</script>

<template>
    <form @submit.prevent="sendMessage">
        <input v-model="input" type="text" :placeholder="props.placeholder" />
        <button :disabled="!input" @click="sendMessage">SEND</button>
    </form>
</template>

<style>
    form {
        flex-grow: 1;
        display: flex;
    }

    input {
        flex-grow: 1;
    }
</style>
