// packages/svelte-live-chat/src/components/Chat.svelte
<script lang="ts">
    import type { ChatMessage } from "repo-types";

    export let messages: ChatMessage[];

    const isLastElement = (index: number) => index === messages.length - 1;
</script>

<div>
    <ul>
        {#each messages as message, index (message.id)}
            <li>
                <slot {message} scrollIntoView={isLastElement(index)} name="message" />
            </li>
        {/each}
    </ul>

    <slot name="input" />
</div>

<style lang="scss" scoped>
    ul {
        list-style-type: none;
        width: 600px;
        height: 400px;
        overflow-y: scroll;

        li {
            display: flex;
        }
    }
</style>

// packages/vue3-live-chat/src/components/Chat.vue
<script setup lang="ts">
import type { ChatMessage } from "repo-types";
import ChatMessageComponent from "./ChatMessage.vue";
import ChatInput from "./ChatInput.vue";

interface Props {
    isColorBlind: boolean,
    messages: Array<ChatMessage>,
    messageHandler: (message: string) => void
}

const props = defineProps<Props>();

const isLastElement = (index: number) => index === props.messages.length - 1;
</script>

<template>
    <div>
        <ul>
            <li
            v-for="(message, index) of props.messages" 
            :key="message.id">
                <ChatMessageComponent
                    :scrollIntoView="isLastElement(index)"
                    :message="message"
                />
            </li>
        </ul>
        <ChatInput
            @submit-message="($event) => messageHandler($event)" 
            placeholder="Send a tweet" 
            :is-disabled="false" />
    </div>
</template>

<style scoped>
    ul {
        min-height: 100%;
        list-style: none;
        flex-grow: 1;
        display: flex;
        flex-direction: column;
        background-color: rgba(0, 0, 0, .1);
        padding: 1.5rem;
        overflow-y: scroll;
    }

    div {
        display: flex;
        flex-direction: column;
        flex-grow: 1;
    }

    ul li {
        padding: .25rem;
    }
</style>
