// packages/solidjs-live-chat/src/components/ChatMessage.tsx
import { Component, onMount, Ref } from 'solid-js';
import { ChatMessage as ChatMessageType, Emoji } from 'repo-types/index';
import Username from './Username';

interface Props {
    scrollIntoView: boolean;
    message: ChatMessageType;
    isColorBlind: boolean;
}

const ChatMessage: Component<Props> = (props) => {

    const appendEmojis = (msg: string) => {
        Object.keys(Emoji).forEach(key => msg = msg.replaceAll(key, Emoji[key]));
        return msg;
    };

    let messageRef: HTMLSpanElement | undefined;

    onMount(() => {
        if(props.scrollIntoView) {
            messageRef?.scrollIntoView({ behavior: "smooth" });
        }
    });

    return (
        <span ref={messageRef}>
            <Username
                tier={props.message.user.tier}
                username={props.message.user.username}
                isColorBlind={props.isColorBlind} /> :
            { appendEmojis(props.message.payload) }
        </span>
    );
};

export default ChatMessage;

// packages/vue3-live-chat/src/components/ChatMessage.vue
<script setup lang="ts">
import { ChatMessage, Emoji } from "repo-types";
import { onMounted, Ref, ref } from "vue";
import Username from "./Username.vue";

const props = defineProps<{ scrollIntoView: boolean, isColorBlind: boolean, message: ChatMessage }>();
const chatMessage: Ref<HTMLSpanElement | null> = ref(null);

const appendEmojis = (msg: string) => {
    Object.keys(Emoji).forEach(key => msg = msg.replaceAll(key, Emoji[key]));
    return msg;
};

onMounted(() => {
    if(chatMessage.value && props.scrollIntoView) {
        chatMessage.value.scrollIntoView({ behavior: "smooth" });
    }
});
</script>

<template>
    <span ref="chatMessage">
        <Username
            :is-color-blind="isColorBlind"
            :username="props.message.user.username" 
            :tier="props.message.user.tier" />
        <span> : </span>
        <span>{{ appendEmojis(props.message.payload) }}</span>
    </span>
</template>
