// packages/react18-live-chat/src/components/Chat.tsx
import { FunctionComponent } from "react";
import { ChatMessage as ChatMessageType } from "repo-types";
import ChatMessage from "./ChatMessage";
import React from "react";
import ChatInput from "./ChatInput";
import "./ChatInput.css";

interface Props {
    isColorBlind: boolean;
    messages: ChatMessageType[];
    messageHandler: (msg: string) => void;
}

const Chat: FunctionComponent<Props> = ({ isColorBlind, messageHandler, messages }) => {

    const style: React.CSSProperties = {
        display: "flex",
        flexDirection: "column",
        padding: "1rem 0 1rem 1rem",
        gap: ".5rem",
        overflowY: "scroll",
        width: "600px",
        height: "400px"
    };

    const isLastElement = (index: number) => index === messages.length - 1;

    return (
        <>
            <div style={style}>
                {
                    messages.map((m, index) => <ChatMessage
                        key={m.id}
                        isColorBlind={isColorBlind}
                        message={m}
                        scrollIntoView={isLastElement(index)} />)
                }
            </div>
            <div style={{ padding: "0 0 0 1rem" }}>
                <ChatInput
                    messageHandler={messageHandler}
                    placeholder="Send your regards" />
            </div>
        </>
    );
}

export default Chat;

// packages/vue3-live-chat/src/components/Chat.vue
<script setup lang="ts">
import type { ChatMessage } from "repo-types";
import ChatMessageComponent from "./ChatMessage.vue";
import ChatInput from "./ChatInput.vue";

interface Props {
    isColorBlind: boolean,
    messages: Array<ChatMessage>,
    messageHandler: (message: string) => void
}

const props = defineProps<Props>();

const isLastElement = (index: number) => index === props.messages.length - 1;
</script>

<template>
    <div>
        <ul>
            <li
            v-for="(message, index) of props.messages" 
            :key="message.id">
                <ChatMessageComponent
                    :scrollIntoView="isLastElement(index)"
                    :message="message"
                />
            </li>
        </ul>
        <ChatInput
            @submit-message="($event) => messageHandler($event)" 
            placeholder="Send a tweet" 
            :is-disabled="false" />
    </div>
</template>

<style scoped>
    ul {
        min-height: 100%;
        list-style: none;
        flex-grow: 1;
        display: flex;
        flex-direction: column;
        background-color: rgba(0, 0, 0, .1);
        padding: 1.5rem;
        overflow-y: scroll;
    }

    div {
        display: flex;
        flex-direction: column;
        flex-grow: 1;
    }

    ul li {
        padding: .25rem;
    }
</style>
