// packages/react18-live-chat/src/components/Username.tsx
import { FunctionComponent } from "react";

interface Props {
    tier: number;
    username: string;
    isColorBlind: boolean;
}

const Username: FunctionComponent<Props> = ({ tier, username, isColorBlind }) => {

    const bgColor = (tier: number) => {
        const tierColors = ["purple", "blue", "pink", "green", "orange"];
        return tierColors[tier] ?? "grey";
    };

    const computedStyle = {
        borderRadius: "2.5px",
        backgroundColor: isColorBlind ? "black" : bgColor(tier),
        color: "white",
        padding: "0 5px 0 5px"
    };

    return <span style={computedStyle}>{ username }</span>;
};

export default Username;

// packages/vue3-live-chat/src/components/Username.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ tier: number, username: string, isColorBlind: boolean }>();

const bgColor = (tier: number) => {
    const tierColors = ["purple", "blue", "pink", "green", "orange"];
    return tierColors[tier] ?? "grey";
};

const computedStyle = computed(() => ({
    borderRadius: "2.5px",
    backgroundColor: props.isColorBlind ? "black" : bgColor(props.tier),
    color: "white",
    padding: "0 5px 0 5px"
}));
</script>

<template>
     <span :style="computedStyle">{{ username }}</span>
</template>
