// packages/solidjs-live-chat/src/components/ChatMessage.tsx
import { Component, onMount, Ref } from 'solid-js';
import { ChatMessage as ChatMessageType, Emoji } from 'repo-types/index';
import Username from './Username';

interface Props {
    scrollIntoView: boolean;
    message: ChatMessageType;
    isColorBlind: boolean;
}

const ChatMessage: Component<Props> = (props) => {

    const appendEmojis = (msg: string) => {
        Object.keys(Emoji).forEach(key => msg = msg.replaceAll(key, Emoji[key]));
        return msg;
    };

    let messageRef: HTMLSpanElement | undefined;

    onMount(() => {
        if(props.scrollIntoView) {
            messageRef?.scrollIntoView({ behavior: "smooth" });
        }
    });

    return (
        <span ref={messageRef}>
            <Username
                tier={props.message.user.tier}
                username={props.message.user.username}
                isColorBlind={props.isColorBlind} /> :
            { appendEmojis(props.message.payload) }
        </span>
    );
};

export default ChatMessage;

// packages/svelte-live-chat/src/components/ChatMessage.svelte
<script lang="ts">
import { ChatMessage, Emoji } from "repo-types";
import { onMount } from "svelte";
import Username from "./Username.svelte";

export let isColorBlind: boolean;
export let message: ChatMessage;
export let scrollIntoView: boolean;

let elementRef: HTMLSpanElement;

const appendEmojis = (msg: string) => {
    Object.keys(Emoji).forEach(key => msg = msg.replaceAll(key, Emoji[key]));
    return msg;
};

onMount(() => {
    if(scrollIntoView && elementRef) {
        elementRef.scrollIntoView({
            behavior: "smooth",
        });
    }
});
</script>

<span style:line-height="1.5rem" bind:this={elementRef}>
    <Username
        {isColorBlind}
        username={message.user.username}
        tier={message.user.tier} 
    />
    :
    <span>{ appendEmojis(message.payload) }</span>
</span>
