// packages/vue3-live-chat/src/components/Username.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ tier: number, username: string, isColorBlind: boolean }>();

const bgColor = (tier: number) => {
    const tierColors = ["purple", "blue", "pink", "green", "orange"];
    return tierColors[tier] ?? "grey";
};

const computedStyle = computed(() => ({
    borderRadius: "2.5px",
    backgroundColor: props.isColorBlind ? "black" : bgColor(props.tier),
    color: "white",
    padding: "0 5px 0 5px"
}));
</script>

<template>
     <span :style="computedStyle">{{ username }}</span>
</template>

// packages/svelte-live-chat/src/components/Username.svelte
<script lang="ts">

export let isColorBlind: boolean;
export let username: string;
export let tier: number;

const bgColor = (tier: number) => {
        const tierColors = ["purple", "blue", "pink", "green", "orange"];
        return tierColors[tier] ?? "grey";
    };

$: backgroundColor = isColorBlind ? "black" : bgColor(tier);

</script>

<span style:background-color={backgroundColor}>
    { username }
</span>

<style scoped>
    span {
        border-radius: 2.5px;
        color: white;
        padding: 0 5px 0 5px;
    }
</style>
