// packages/solidjs-live-chat/src/components/Username.tsx
import type { Component } from 'solid-js';

interface Props {
    username: string;
    tier: number;
    isColorBlind: boolean;
}

const Username: Component<Props> = (props) => {

    const backgroundColor = (tier: number, isColorBlind: boolean) => {
        if(isColorBlind) return 'black';
        const tierColors = ["purple", "blue", "pink", "green", "orange"];
        return tierColors[tier] ?? "grey";
    };

    return (
        <span
        class="rounded-md px-2 text-white"
        style={{ "background-color": backgroundColor(props.tier, props.isColorBlind) }}>
            { props.username }
        </span>
    );
};

export default Username;

// packages/svelte-live-chat/src/components/Username.svelte
<script lang="ts">

export let isColorBlind: boolean;
export let username: string;
export let tier: number;

const bgColor = (tier: number) => {
        const tierColors = ["purple", "blue", "pink", "green", "orange"];
        return tierColors[tier] ?? "grey";
    };

$: backgroundColor = isColorBlind ? "black" : bgColor(tier);

</script>

<span style:background-color={backgroundColor}>
    { username }
</span>

<style scoped>
    span {
        border-radius: 2.5px;
        color: white;
        padding: 0 5px 0 5px;
    }
</style>
