// packages/solidjs-live-chat/src/components/ChatInput.tsx
import { Component, createSignal } from 'solid-js';

interface Props {
    placeholder: string;
    buttonText: string;
    messageHandler: (msg: string) => void;
}

const ChatInput: Component<Props> = (props) => {

    const [textInputValue, setTextInputValue] = createSignal("");

    const sendMessage = () => {
        props.messageHandler(textInputValue());
        setTextInputValue("");
    };

    return (
        <form class="flex flex-row" onSubmit={(e) => e.preventDefault()}>
            <input
                class="grow-[3] border-slate-600 border rounded rounded-r-none px-2 py-1"
                onChange={(e) => setTextInputValue(e.target.value)}
                value={textInputValue()} 
                type="text" 
                placeholder={ props.placeholder }/>
            <button class="grow-[1] border-slate-800 border rounded rounded-l-none bg-slate-600 text-white px-2 py-1" onClick={sendMessage}>{ props.buttonText }</button>
        </form>
    );
};

export default ChatInput;

// packages/react18-live-chat/src/components/ChatInput.tsx
import { FunctionComponent, useState } from "react";

interface Props {
    messageHandler: (msg: string) => void;
    placeholder: string,
}

const ChatInput: FunctionComponent<Props> = ({ messageHandler, placeholder }) => {

    const [input, setInput] = useState("");

    const sendMessage = () => {
        if(!input) return;
        messageHandler(input);
        setInput("");
    };

    return (
        <form id="chatInput" onSubmit={(e) => e.preventDefault()}>
            <input value={input} onChange={e => setInput(e.target.value)} type="text" placeholder={placeholder} />
            <button disabled={!input} onClick={sendMessage}>SEND</button>
        </form>
    );
};

export default ChatInput;
