// packages/react18-live-chat/src/App.tsx
import { io, Socket } from "socket.io-client";
import { ServerToClientEvents, ClientToServerEvents, ChatMessage } from "repo-types/index";
import { BACKEND_PORT } from "repo-types/env";
import { FunctionComponent, useEffect, useState } from "react";
import Chat from "./components/Chat";
import './App.css';

type SocketConnection = Socket<ServerToClientEvents, ClientToServerEvents>;

let socket: SocketConnection = io(
    `ws://localhost:${BACKEND_PORT}`,
    {
        withCredentials: true,
        extraHeaders: { "my-custom-header": "abcd" }
    }
);;

const App: FunctionComponent = () => {

    const [isConnected, setIsConnected] = useState(socket.connected);
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [isColorBlind, setColorBlindMode] = useState(false);
    const maxMessagesNumber = 20;

    useEffect(() => {

        socket.on("connect", () => setIsConnected(true));
        socket.on("disconnect", () => setIsConnected(false)); 

        socket.on("chatMessage", (msg: ChatMessage) => {
            if(messages.length >= maxMessagesNumber) messages.shift();
            setMessages(msgs => [...msgs, msg]);
        });
        
        return () => {
            socket.off('connect');
            socket.off('disconnect');
            socket.off('chatMessage');
        };
    }, [messages]);

    const messageHandler = (msg: string) => { socket?.emit("sendMessage", msg); };

    return (
        <>
            <span>Connection: { isConnected ? "ON": "OFF" }</span>
            <form style={{ padding: "1rem" }}>
                <input 
                    id="color-blind-mode" 
                    type="checkbox" 
                    checked={isColorBlind}
                    onChange={() => setColorBlindMode(!isColorBlind)}
                />
                <label htmlFor="color-blind-mode">Color blind mode</label>
            </form>
            <Chat 
                isColorBlind={isColorBlind} 
                messageHandler={messageHandler} 
                messages={messages}
            />
        </>
    );
}

export default App;

// packages/vue3-live-chat/src/App.vue
<script setup lang="ts">
import { Socket } from "socket.io-client";
import { ChatMessage, ClientToServerEvents, ServerToClientEvents } from "repo-types";
import { io } from "socket.io-client";
import { onUnmounted, onMounted, ref } from "vue";
import Chat from "./components/Chat.vue";
import { BACKEND_PORT } from "repo-types/env";

let ws: Socket<ServerToClientEvents, ClientToServerEvents> | null = null;

const messages = ref<ChatMessage[]>([]);
const isColorBlind = ref<boolean>(false);
const maxNumberChatMessages = 20;

const onChatMessage = (message: ChatMessage) => {
    if(messages.value.length >= maxNumberChatMessages) messages.value.shift();
    messages.value = [...messages.value, message];
};

onMounted(() => {
    ws = io(`ws://localhost:${BACKEND_PORT}`, {
        withCredentials: true,
        extraHeaders: { "my-custom-header": "abcd" }
    });
    ws.on("chatMessage", onChatMessage);
});

onUnmounted(() => {
    ws?.disconnect();
    ws = null;
});

const messageHandler = (msg: string) => ws?.emit("sendMessage", msg);

</script>

<template>
    <form>
        <input id="color-blind-mode" type="checkbox" v-model="isColorBlind" />
        <label for="color-blind-mode">Color blind mode</label>
    </form>
    <main :style="{ width: '500px', minHeight: '500px', maxHeight: '500px', display: 'flex'}">
        <Chat
        :message-handler="messageHandler"
        :messages="messages" 
        :is-color-blind="isColorBlind" />
    </main>
</template>

<style>
    * {
        padding: 0;
        margin: 0;
    }

    body {
        min-height: 100vh;
        display: grid;
        place-items: center;
    }
</style>
