// packages/react18-live-chat/src/components/Chat.tsx
import { FunctionComponent } from "react";
import { ChatMessage as ChatMessageType } from "repo-types";
import ChatMessage from "./ChatMessage";
import React from "react";
import ChatInput from "./ChatInput";
import "./ChatInput.css";

interface Props {
    isColorBlind: boolean;
    messages: ChatMessageType[];
    messageHandler: (msg: string) => void;
}

const Chat: FunctionComponent<Props> = ({ isColorBlind, messageHandler, messages }) => {

    const style: React.CSSProperties = {
        display: "flex",
        flexDirection: "column",
        padding: "1rem 0 1rem 1rem",
        gap: ".5rem",
        overflowY: "scroll",
        width: "600px",
        height: "400px"
    };

    const isLastElement = (index: number) => index === messages.length - 1;

    return (
        <>
            <div style={style}>
                {
                    messages.map((m, index) => <ChatMessage
                        key={m.id}
                        isColorBlind={isColorBlind}
                        message={m}
                        scrollIntoView={isLastElement(index)} />)
                }
            </div>
            <div style={{ padding: "0 0 0 1rem" }}>
                <ChatInput
                    messageHandler={messageHandler}
                    placeholder="Send your regards" />
            </div>
        </>
    );
}

export default Chat;

// packages/solidjs-live-chat/src/components/Chat.tsx
import { Component, createSignal, createMemo, For, Accessor } from 'solid-js';
import type { ChatMessage as ChatMessageType } from 'repo-types/index';
import ChatInput from './ChatInput';
import ChatMessage from './ChatMessage';
import ColorBlindMode from './ColorBlindMode';

interface Props {
    chatMessageComponent: typeof ChatMessage,
    chatInputComponent: typeof ChatInput,
    colorBlindModeComponent: typeof ColorBlindMode,
    messageHandler: (msg: string) => void,
    messages: ChatMessageType[],
    isColorBlind: boolean
}

const Chat: Component<Props> = (props) => {
        
    const [isColorBlindMutable, setIsColorBlind] = createSignal(props.isColorBlind);

    const createMessageMemo = (message: ChatMessageType, index: Accessor<number>) => (
        createMemo(() => props.chatMessageComponent(
            { 
                message, 
                isColorBlind: isColorBlindMutable(), 
                scrollIntoView: index() === props.messages.length -1
            }
        ))
    );

    return (
        <div class="flex flex-col gap-4">
            { 
                props.colorBlindModeComponent({ isColorBlind: isColorBlindMutable(), setIsColorBlind }) 
            }
            <div style={{ height: "400px", width: "600px" }} class="flex flex-col overflow-y-scroll">
                <For each={props.messages}>
                    { createMessageMemo }
                </For>
            </div>
            { 
                props.chatInputComponent(
                    { 
                        buttonText: "Send Nudes", 
                        placeholder: "Send a tweet", 
                        messageHandler: props.messageHandler
                    }
                ) 
            }
        </div>
    );
};

export default Chat;
