// packages/svelte-live-chat/src/components/ChatInput.svelte
<script lang="ts">
    export let messageHandler: (msg: string) => void;
    export let placeholder: string = "Placeholder";
    let input: string = "";

    const sendMessage = () => {
        messageHandler(input);
        input = "";
    };
</script>

<form on:submit|preventDefault>
    <input bind:value={input} type="text" placeholder={placeholder} />
    <button disabled={!input} on:click={sendMessage}>SEND</button>
</form>

<style lang="scss" scoped>
    form {
        display: flex;
        
        input {
            flex-grow: 3;
        }

        button {
            flex-grow: 1;
        }

        > * {
            padding: .25rem;
        }
    }
</style>

// packages/angular14-live-chat/src/app/chat-input/chat-input.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-chat-input',
    templateUrl: './chat-input.component.html',
    styleUrls: ['./chat-input.component.scss']
})
export class ChatInputComponent {

    @Input() placeholder!: string;
    @Input() messageHandler!: (msg: string) => void;

    constructor() { }

    sendMessage(el: HTMLInputElement) {
        this.messageHandler(el.value);
        el.value = "";
    }
}

<form id="chatInput" (submit)="$event.preventDefault()">
    <input #messageInput type="text" [placeholder]="placeholder" />
    <button [disabled]="!messageInput.value" (click)="sendMessage(messageInput)">SEND</button>
</form>
